api_platform:
    title: Zadanie rekrutacyjne Web24 - Michał Dąbrowski
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
